"""updated database tables

Revision ID: 2f155303be63
Revises: dae2bd0fa1f0
Create Date: 2026-02-04 18:57:01.076091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f155303be63'
down_revision: Union[str, Sequence[str], None] = 'dae2bd0fa1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_table', sa.Column('rendered_notification', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('notification_table', 'template_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('notification_table', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_column('notification_table', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_table', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('notification_table', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('notification_table', 'template_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('notification_table', 'rendered_notification')
    # ### end Alembic commands ###
