"""added forign id to template table for ownership

Revision ID: 91c0f1d2e581
Revises: ed216bfa52cf
Create Date: 2026-01-31 11:44:10.739280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c0f1d2e581'
down_revision: Union[str, Sequence[str], None] = 'ed216bfa52cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_table', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'template_table', 'api_key_table', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'template_table', type_='foreignkey')
    op.drop_column('template_table', 'owner_id')
    # ### end Alembic commands ###
