"""added unique to api table name

Revision ID: 921f9c2a8909
Revises: 91c0f1d2e581
Create Date: 2026-02-01 18:01:43.960340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921f9c2a8909'
down_revision: Union[str, Sequence[str], None] = '91c0f1d2e581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'api_key_table', ['apikey_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_key_table', type_='unique')
    # ### end Alembic commands ###
