"""chnaged template table

Revision ID: c1489dbfd7f1
Revises: 
Create Date: 2026-01-31 11:23:32.725837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1489dbfd7f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('apikey_name', sa.String(), nullable=False),
    sa.Column('apikey_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apikey_hash')
    )
    op.create_table('template_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('template_body', sa.Text(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_address', sa.String(length=255), nullable=False),
    sa.Column('notification_type', sa.Enum('email', 'sms', name='notification_type'), nullable=False),
    sa.Column('recipient_address', sa.String(length=255), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'HIGH', name='priority_level'), nullable=False),
    sa.Column('callback_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'ERRORED', name='notification_status'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_unprocessed_notification', 'notification_table', ['priority', 'created_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index_unprocessed_notification', table_name='notification_table', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('notification_table')
    op.drop_table('template_table')
    op.drop_table('api_key_table')
    # ### end Alembic commands ###
