"""updated notification table

Revision ID: cf1d3357f345
Revises: 2f155303be63
Create Date: 2026-02-08 11:16:39.507842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf1d3357f345'
down_revision: Union[str, Sequence[str], None] = '2f155303be63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_table', sa.Column('custom_template', sa.Text(), nullable=True))
    op.add_column('notification_table', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('notification_table', 'rendered_notification')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_table', sa.Column('rendered_notification', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('notification_table', 'payload')
    op.drop_column('notification_table', 'custom_template')
    # ### end Alembic commands ###
