"""updated template table

Revision ID: dae2bd0fa1f0
Revises: 921f9c2a8909
Create Date: 2026-02-02 23:06:57.185259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dae2bd0fa1f0'
down_revision: Union[str, Sequence[str], None] = '921f9c2a8909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_table', 'callback_url')
    op.add_column('template_table', sa.Column('template_type', sa.String(length=50), nullable=False))
    op.add_column('template_table', sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('template_table', 'title')
    op.drop_column('template_table', 'subject')
    op.drop_column('template_table', 'template_body')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_table', sa.Column('template_body', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('template_table', sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('template_table', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('template_table', 'content')
    op.drop_column('template_table', 'template_type')
    op.add_column('notification_table', sa.Column('callback_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
